[book]
authors = ["Varun Malladi"]
language = "en"
multilingual = false
src = "src"
title = "rustconomicon"
description = "building a rust compiler in rust"

[output.html]
site-url = "/rustconomicon/"
